---
title: "R Eğitim"
author: "Melike Dönertaş"
date: "22-03-2021"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "22 Mart 2021 tarihinde Bioinforange tarafından düzenlenen Bioinfoconference kapsamında verilen R Eğitim çalıştay materyalini içerir."
---

# Bilgilendirme {.unnumbered}

22 Mart 2021 tarihinde Bioinforange tarafından düzenlenen Bioinfoconference kapsamında verilen R Eğitim çalıştay materyalini içerir. Çalıştay materyali Melike Dönertaş tarafından hazırlanmıştır, öneri ve düzeltmeler için konu başlığında "[Bioinforange R Eğitim]" kullanarak [email](mailto:donertas.melike@gmail.com) ile ulaşabilirsiniz (lütfen sadece öneri ve düzeltmeler için arkadaşlar, çalıştay boyutunu göz önünde bulundurursanız hatalarınıza email ile yardımcı olmam imkansız. Yardım için aşağıdaki başlığa bakabilirsiniz).

## Yardım {.unnumbered}

R konusunda karşılaştığınız sorular için öncelikle aldığınız hata ve uyarıları incelemenizi, `?` operatörünü veya `help()` komutunu kullanarak fonksiyon, veriseti ve obje yardım sayfalarına bakmanızı, R sıkça sorulan sorular kitapçıklarına sorularınızın dahil olup olmadığını kontrol etmenizi ([Genel SSS](https://cran.r-project.org/doc/FAQ/R-FAQ.html), [Windows'a özgü SSS](https://cran.r-project.org/bin/windows/base/rw-FAQ.html), [Mac OS'a özgü SSS](https://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html)), bir paket kullanıyorsanız ve sorunuz bununla ilgiliyse paket yardım ve kullanım örnekleri dosyalarını incelemenizi, ve eğer bu aşamalardan sonra hala cevap bulamadıysanız sorunuzu "[Nasıl güzel soru sorulur?](https://stackoverflow.com/help/how-to-ask)" yönergesine göz attıktan sonra [Stack Overflow R bölümü](https://stackoverflow.com/questions/tagged/r)ne sormanızı tavsiye ederim. Alternatif olarak, kodlama konusunda yardımlaşma platformlarına ([RSG Türkiye](https://rsgturkey.com/)'nin Slack kanalı gibi[^index-1]) sorularınızı gönderebilirsiniz.

[^index-1]: bu şekilde başka platformlar biliyorsanız lütfen bildirin, güncelleyebilirim
