<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Bölüm 5 Veri on isleme basamaklari | R Eğitim</title>
  <meta name="description" content="22 Mart 2021 tarihinde Bioinforange tarafından düzenlenen Bioinfoconference kapsamında verilen R Eğitim çalıştay materyalini içerir." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Bölüm 5 Veri on isleme basamaklari | R Eğitim" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="22 Mart 2021 tarihinde Bioinforange tarafından düzenlenen Bioinfoconference kapsamında verilen R Eğitim çalıştay materyalini içerir." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Bölüm 5 Veri on isleme basamaklari | R Eğitim" />
  
  <meta name="twitter:description" content="22 Mart 2021 tarihinde Bioinforange tarafından düzenlenen Bioinfoconference kapsamında verilen R Eğitim çalıştay materyalini içerir." />
  

<meta name="author" content="Melike Dönertaş" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="insan-prefrontal-korteksinde-gen-ifadesinin-zamansal-dinamikleri.html"/>
<link rel="next" href="temel-bilesenler-analizi.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R Eğitim Çalıştayı</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bilgilendirme</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#yardım"><i class="fa fa-check"></i>Yardım</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="çalıştay-içeriği.html"><a href="çalıştay-içeriği.html"><i class="fa fa-check"></i><b>1</b> Çalıştay içeriği</a></li>
<li class="chapter" data-level="2" data-path="giriş.html"><a href="giriş.html"><i class="fa fa-check"></i><b>2</b> Giriş</a>
<ul>
<li class="chapter" data-level="2.1" data-path="giriş.html"><a href="giriş.html#r-kurulumu"><i class="fa fa-check"></i><b>2.1</b> R Kurulumu</a></li>
<li class="chapter" data-level="2.2" data-path="giriş.html"><a href="giriş.html#rstudio"><i class="fa fa-check"></i><b>2.2</b> RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="giriş.html"><a href="giriş.html#başlangıç"><i class="fa fa-check"></i><b>2.3</b> Başlangıç</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html"><i class="fa fa-check"></i><b>3</b> Temel Bilgiler</a>
<ul>
<li class="chapter" data-level="3.1" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#rstudio-projesi"><i class="fa fa-check"></i><b>3.1</b> RStudio projesi</a></li>
<li class="chapter" data-level="3.2" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#hesap-makinesi-olarak-r"><i class="fa fa-check"></i><b>3.2</b> Hesap makinesi olarak R</a></li>
<li class="chapter" data-level="3.3" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#fonksiyonlar"><i class="fa fa-check"></i><b>3.3</b> Fonksiyonlar</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#yardım-almak"><i class="fa fa-check"></i><b>3.3.1</b> Yardım almak</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#değişkenlerle-çalışmak"><i class="fa fa-check"></i><b>3.4</b> Değişkenlerle çalışmak</a></li>
<li class="chapter" data-level="3.5" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#rda-objeler"><i class="fa fa-check"></i><b>3.5</b> R’da objeler</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#obje-türleri"><i class="fa fa-check"></i><b>3.5.1</b> Obje türleri</a></li>
<li class="chapter" data-level="3.5.2" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#vektör"><i class="fa fa-check"></i><b>3.5.2</b> Vektör</a></li>
<li class="chapter" data-level="3.5.3" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#liste"><i class="fa fa-check"></i><b>3.5.3</b> Liste</a></li>
<li class="chapter" data-level="3.5.4" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#matris"><i class="fa fa-check"></i><b>3.5.4</b> Matris</a></li>
<li class="chapter" data-level="3.5.5" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#faktör"><i class="fa fa-check"></i><b>3.5.5</b> Faktör</a></li>
<li class="chapter" data-level="3.5.6" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#data-frame"><i class="fa fa-check"></i><b>3.5.6</b> Data frame</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="temel-bilgiler.html"><a href="temel-bilgiler.html#paketler"><i class="fa fa-check"></i><b>3.6</b> Paketler</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="insan-prefrontal-korteksinde-gen-ifadesinin-zamansal-dinamikleri.html"><a href="insan-prefrontal-korteksinde-gen-ifadesinin-zamansal-dinamikleri.html"><i class="fa fa-check"></i><b>4</b> Insan prefrontal korteksinde gen ifadesinin zamansal dinamikleri</a>
<ul>
<li class="chapter" data-level="4.1" data-path="insan-prefrontal-korteksinde-gen-ifadesinin-zamansal-dinamikleri.html"><a href="insan-prefrontal-korteksinde-gen-ifadesinin-zamansal-dinamikleri.html#calistay-icin-verinin-on-hazirligi"><i class="fa fa-check"></i><b>4.1</b> Calistay icin verinin on hazirligi</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html"><i class="fa fa-check"></i><b>5</b> Veri on isleme basamaklari</a>
<ul>
<li class="chapter" data-level="5.1" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#read.csv-ve-readrds-ile-veri-okuma"><i class="fa fa-check"></i><b>5.1</b> <code>read.csv()</code> ve <code>readRDS()</code> ile veri okuma</a></li>
<li class="chapter" data-level="5.2" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#kesifci-veri-analizi"><i class="fa fa-check"></i><b>5.2</b> Kesifci veri analizi</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#histogram"><i class="fa fa-check"></i><b>5.2.1</b> Histogram</a></li>
<li class="chapter" data-level="5.2.2" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#boxplot"><i class="fa fa-check"></i><b>5.2.2</b> Boxplot</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#probesetid---gen-eslestirmesi"><i class="fa fa-check"></i><b>5.3</b> ProbesetID - Gen eslestirmesi</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#in-operatoru"><i class="fa fa-check"></i><b>5.3.1</b> <code>%in%</code> operatoru</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#quantile-normalization"><i class="fa fa-check"></i><b>5.4</b> Quantile Normalization</a></li>
<li class="chapter" data-level="5.5" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#ornek-bilgisini-duzenleme"><i class="fa fa-check"></i><b>5.5</b> Ornek bilgisini duzenleme</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#yas-verisinin-duzenlenmesi"><i class="fa fa-check"></i><b>5.5.1</b> Yas verisinin duzenlenmesi</a></li>
<li class="chapter" data-level="5.5.2" data-path="veri-on-isleme-basamaklari.html"><a href="veri-on-isleme-basamaklari.html#biyolojik-cinsiyet-verisinin-duzenlenmesi"><i class="fa fa-check"></i><b>5.5.2</b> Biyolojik cinsiyet verisinin duzenlenmesi</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="temel-bilesenler-analizi.html"><a href="temel-bilesenler-analizi.html"><i class="fa fa-check"></i><b>6</b> Temel bilesenler analizi</a></li>
<li class="chapter" data-level="7" data-path="yasla-degisim-analizi.html"><a href="yasla-degisim-analizi.html"><i class="fa fa-check"></i><b>7</b> Yasla degisim analizi</a></li>
<li class="chapter" data-level="8" data-path="biyolojik-cinsiyete-gore-farklilik-gosteren-gen-analizi.html"><a href="biyolojik-cinsiyete-gore-farklilik-gosteren-gen-analizi.html"><i class="fa fa-check"></i><b>8</b> Biyolojik cinsiyete gore farklilik gosteren gen analizi</a></li>
<li class="chapter" data-level="9" data-path="kaynak-onerileri.html"><a href="kaynak-onerileri.html"><i class="fa fa-check"></i><b>9</b> Kaynak onerileri</a>
<ul>
<li class="chapter" data-level="9.1" data-path="kaynak-onerileri.html"><a href="kaynak-onerileri.html#online-ders"><i class="fa fa-check"></i><b>9.1</b> Online ders</a></li>
<li class="chapter" data-level="9.2" data-path="kaynak-onerileri.html"><a href="kaynak-onerileri.html#kitaplar"><i class="fa fa-check"></i><b>9.2</b> Kitaplar</a></li>
<li class="chapter" data-level="9.3" data-path="kaynak-onerileri.html"><a href="kaynak-onerileri.html#diger"><i class="fa fa-check"></i><b>9.3</b> Diger</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R Eğitim</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="veri-on-isleme-basamaklari" class="section level1" number="5">
<h1><span class="header-section-number">Bölüm 5</span> Veri on isleme basamaklari</h1>
<p>Veriyi GEO’dan ifade matrisi, metadata yani bireylere dair bilginin bulundugu bir tablo, ve feature data yani probeset-gen eslesmelerinin verildigi bir tablo olarak kaydettim. Simdi bunlari okuyarak baslayacagiz. Ilk olarak gen ifade verisiyle baslayalim.</p>
<div id="read.csv-ve-readrds-ile-veri-okuma" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> <code>read.csv()</code> ve <code>readRDS()</code> ile veri okuma</h2>
<p><code>read.csv</code> fonksiyonu hem URL’den okuma hem de bilgisayarimizdaki bir dosyadan okuma yapmamizi saglar. Dosyayi <a href="https://github.com/mdonertas/20210322_REgitim/tree/master/data">github repomdan</a> indirip, fonksiyona <code>file =</code> degiskeni olarak bilgisayarinizda indirdiginiz yeri vererek okuyabilirsiniz. Simdi kolaylik olmasi acisindan direkt olarak github repomdan okuyacagiz. Bu fonksiyon ayrica baska argumanlar da aliyor. <code>header</code> dosyada sutun isimlerinin yer alip almadigini belirtmek icin kullaniliyor ve mantiksal bir arguman yani <code>TRUE</code> ya da <code>FALSE</code> degerlerini alabilir. Kullanacagimiz bir diger arguman ise <code>row.names =</code>, bu da satir isimlerinin hangi sutunda yer aldigini belirtmemiz icin gerekli. Eger bu argumani kullanmazsak, matrisimizin satir isimleri de bir sutun olarak okunacaktir.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="veri-on-isleme-basamaklari.html#cb170-1" aria-hidden="true" tabindex="-1"></a>expr <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&#39;https://github.com/mdonertas/20210322_REgitim/raw/master/data/expressionmatrix.csv&#39;</span>, </span>
<span id="cb170-2"><a href="veri-on-isleme-basamaklari.html#cb170-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">header =</span> T, </span>
<span id="cb170-3"><a href="veri-on-isleme-basamaklari.html#cb170-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">row.names =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Ilk 6 satir ve 4 sutuna bakalim:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="veri-on-isleme-basamaklari.html#cb171-1" aria-hidden="true" tabindex="-1"></a>expr[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span></code></pre></div>
<pre><code>##                    GSM749899  GSM749900 GSM749901  GSM749902
## HEEBO-002-CTRL2I1  -1.455124 -2.6244200 -1.904436 -1.5793507
## HEEBO-002-CTRL2I10  1.044670  0.4490985  0.619243  0.1930628
## HEEBO-002-CTRL2I11  1.164344  1.5833201  1.150024  1.5764080
## HEEBO-002-CTRL2I14  1.597227  1.4105770  1.469449  2.6433802
## HEEBO-002-CTRL2I15 -1.454337 -1.9784923 -1.485409 -1.5038039
## HEEBO-002-CTRL2I16  1.396667  0.7461117  1.212514  0.6586667</code></pre>
<p>Her sey yolunda gozukuyor ama bir de bu objenin daha onceden ogrendigimiz gibi <code>class</code>ina bakalim:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="veri-on-isleme-basamaklari.html#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(expr)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>Genellikle <code>read.csv</code> fonksiyonu bir data.frame olusturur. Biz bu objede kimi matris operasyonlari yapmak istiyoruz ve verimiz de sadece numerik degerlerden olusuyor. O yuzden bunu matrise donusturebiliriz. Bunun icin <code>as.matrix</code> yani ‘matrix olarak’ fonksiyonunu kullanabiliriz.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="veri-on-isleme-basamaklari.html#cb175-1" aria-hidden="true" tabindex="-1"></a>expr <span class="ot">=</span> <span class="fu">as.matrix</span>(expr)</span></code></pre></div>
<p>Tekrar ilk birkac satir sutun ve class kontrolumuzu yapalim:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="veri-on-isleme-basamaklari.html#cb176-1" aria-hidden="true" tabindex="-1"></a>expr[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span></code></pre></div>
<pre><code>##                    GSM749899  GSM749900 GSM749901  GSM749902
## HEEBO-002-CTRL2I1  -1.455124 -2.6244200 -1.904436 -1.5793507
## HEEBO-002-CTRL2I10  1.044670  0.4490985  0.619243  0.1930628
## HEEBO-002-CTRL2I11  1.164344  1.5833201  1.150024  1.5764080
## HEEBO-002-CTRL2I14  1.597227  1.4105770  1.469449  2.6433802
## HEEBO-002-CTRL2I15 -1.454337 -1.9784923 -1.485409 -1.5038039
## HEEBO-002-CTRL2I16  1.396667  0.7461117  1.212514  0.6586667</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="veri-on-isleme-basamaklari.html#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(expr)</span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<p>Arraylerden baslangicta bahsetmemistim, kullanimi cok asiri yaygin degil ama bunlar da 1 ya da daha fazla boyutlu vektorler olarak dusunulebilir, yani iki boyutlusu matris ama daha fazla boyutlu array olusturmak mumkun.</p>
<p>Simdi bir de matrisimizin boyutlarina bakalim. Bunu ya satir (<code>nrow()</code>) ve sutun sayisini (<code>ncol()</code>) yazdirarak ya da <code>dim()</code> fonksiyonu ile yapabiliriz.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="veri-on-isleme-basamaklari.html#cb180-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(expr)</span></code></pre></div>
<pre><code>## [1] 30176</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="veri-on-isleme-basamaklari.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(expr)</span></code></pre></div>
<pre><code>## [1] 269</code></pre>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="veri-on-isleme-basamaklari.html#cb184-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(expr)</span></code></pre></div>
<pre><code>## [1] 30176   269</code></pre>
<p>Matrisimizde 30176 satir, 269 sutun var - yani 30176 probeset ID, 269 ornek. Daha fazla ilerlemeden once bir veri okuma sekli daha gostermek istiyorum.</p>
<p>Alternatif olarak ayni veriyi bir .rds - R objesi olarak da kaydetmistim. Onu okumak icin de <code>readRDS()</code> fonksiyonunu kullanabiliriz. Bunun avantaji verinizin bir csv dosyasina kaydedilerek olasi bozulmalarini engellemenin yani sira, obje turunu vs. de koruyabilirsiniz.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="veri-on-isleme-basamaklari.html#cb186-1" aria-hidden="true" tabindex="-1"></a>expr <span class="ot">=</span> <span class="fu">readRDS</span>(<span class="at">file =</span> <span class="st">&#39;./data/expressionmatrix.rds&#39;</span>)</span>
<span id="cb186-2"><a href="veri-on-isleme-basamaklari.html#cb186-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(expr)</span></code></pre></div>
<pre><code>## [1] &quot;matrix&quot; &quot;array&quot;</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="veri-on-isleme-basamaklari.html#cb188-1" aria-hidden="true" tabindex="-1"></a>expr[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span></code></pre></div>
<pre><code>##                    GSM749899  GSM749900 GSM749901  GSM749902
## HEEBO-002-CTRL2I1  -1.455124 -2.6244200 -1.904436 -1.5793507
## HEEBO-002-CTRL2I10  1.044670  0.4490985  0.619243  0.1930628
## HEEBO-002-CTRL2I11  1.164344  1.5833201  1.150024  1.5764080
## HEEBO-002-CTRL2I14  1.597227  1.4105770  1.469449  2.6433802
## HEEBO-002-CTRL2I15 -1.454337 -1.9784923 -1.485409 -1.5038039
## HEEBO-002-CTRL2I16  1.396667  0.7461117  1.212514  0.6586667</code></pre>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="veri-on-isleme-basamaklari.html#cb190-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(expr)</span></code></pre></div>
<pre><code>## [1] 30176   269</code></pre>
<p>Gordugunuz gibi bu dosyayi okudugumuzda veriyi direkt olarak matrix olarak okuyabildik ve data.frame’den donusturmek zorunda kalmadik.</p>
</div>
<div id="kesifci-veri-analizi" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Kesifci veri analizi</h2>
<p>Daha ileri gecmeden hemen bu asamada cok kisaca verimiz neye benziyor bakabiliriz. Bunun icin temel bir kac gorsellestirme fonksiyonu kullanacagiz.</p>
<div id="histogram" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Histogram</h3>
<p>Ilk olarak verimizin dagilimi nedir, ne gibi degerler var bunlara bakalim. Bunun icin histogram kullanabiliriz, ve ilk olarak temel Rda histogram cizmeyi gorelim.</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="veri-on-isleme-basamaklari.html#cb192-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(expr)</span></code></pre></div>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>Bu sekilde, hangi bireyin veya genin verisi olduguna bakmaksizin tum degerlerin bir histogramini aliriz. Bu histogram cogu gen ekpresyon verisinde alacaginiz ham veri grafiginden cok farkli, bunun sebebi bunun two channel microarray olmasi ve loess normalizasyonu gibi kimi normalizasyon asamalarindan da gecirilmis olmasi.</p>
<p>Buna bakmak oldukca kolaydi, ama ben genel olarak <code>ggplot2</code> paketinin gorsellestirmelerini kullaniyorum ve herkese en bastan itibaren ggplot ogrenmesini tavsiye ediyorum. Basit grafiklerde biraz zahmetli gelse de kompleks yayina hazir figur olusturmak icin cok ciddi kolaylik sagliyor. <code>ggplot2</code> data.frame objesiyle calisir, oysa bu bir matris. Bu yuzden ufak bir degisiklik yapmamiz lazim:</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="veri-on-isleme-basamaklari.html#cb193-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb193-2"><a href="veri-on-isleme-basamaklari.html#cb193-2" aria-hidden="true" tabindex="-1"></a>mydat <span class="ot">=</span> reshape2<span class="sc">::</span><span class="fu">melt</span>(expr)</span>
<span id="cb193-3"><a href="veri-on-isleme-basamaklari.html#cb193-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mydat, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb193-4"><a href="veri-on-isleme-basamaklari.html#cb193-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="veri-on-isleme-basamaklari.html#cb195-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mydat, <span class="fu">aes</span>(<span class="at">x =</span> value)) <span class="sc">+</span></span>
<span id="cb195-2"><a href="veri-on-isleme-basamaklari.html#cb195-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">&#39;gray60&#39;</span>, <span class="at">bins =</span> <span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb195-3"><a href="veri-on-isleme-basamaklari.html#cb195-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&#39;Probeset Expression&#39;</span>) <span class="sc">+</span></span>
<span id="cb195-4"><a href="veri-on-isleme-basamaklari.html#cb195-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&#39;Count&#39;</span>) <span class="sc">+</span></span>
<span id="cb195-5"><a href="veri-on-isleme-basamaklari.html#cb195-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
</div>
<div id="boxplot" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Boxplot</h3>
<p>Simdi de ilk birkac bireyin gen anlatim profillerine bakalim. Ilk once base R gorsellestirme fonksiyonu ile:</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="veri-on-isleme-basamaklari.html#cb196-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(expr[,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>Ayni grafigi ilk bir kac gen icin cizmek isteyecek olsak, hem matrisi subset etmemiz hem de transpoze etmemiz gerekir. Bunu <code>t()</code> fonksiyonu ile kolaylikla yapabiliriz:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="veri-on-isleme-basamaklari.html#cb197-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">t</span>(expr[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,]))</span></code></pre></div>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<p>Aynisini ggplot ile yapalim:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="veri-on-isleme-basamaklari.html#cb198-1" aria-hidden="true" tabindex="-1"></a>mydat <span class="ot">=</span> reshape2<span class="sc">::</span><span class="fu">melt</span>(expr[,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span>
<span id="cb198-2"><a href="veri-on-isleme-basamaklari.html#cb198-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mydat)</span></code></pre></div>
<pre><code>##                 Var1      Var2     value
## 1  HEEBO-002-CTRL2I1 GSM749899 -1.455124
## 2 HEEBO-002-CTRL2I10 GSM749899  1.044670
## 3 HEEBO-002-CTRL2I11 GSM749899  1.164344
## 4 HEEBO-002-CTRL2I14 GSM749899  1.597227
## 5 HEEBO-002-CTRL2I15 GSM749899 -1.454337
## 6 HEEBO-002-CTRL2I16 GSM749899  1.396667</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="veri-on-isleme-basamaklari.html#cb200-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mydat,<span class="fu">aes</span>(<span class="at">x =</span> Var2, <span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb200-2"><a href="veri-on-isleme-basamaklari.html#cb200-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.size =</span> <span class="fl">0.01</span>, <span class="at">outlier.color =</span> <span class="st">&#39;gray&#39;</span>, <span class="at">color =</span> <span class="st">&#39;darkred&#39;</span>) <span class="sc">+</span></span>
<span id="cb200-3"><a href="veri-on-isleme-basamaklari.html#cb200-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb200-4"><a href="veri-on-isleme-basamaklari.html#cb200-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&#39;Probeset Expression Value&#39;</span>)</span></code></pre></div>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="veri-on-isleme-basamaklari.html#cb201-1" aria-hidden="true" tabindex="-1"></a>mydat <span class="ot">=</span> reshape2<span class="sc">::</span><span class="fu">melt</span>(expr[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,])</span>
<span id="cb201-2"><a href="veri-on-isleme-basamaklari.html#cb201-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mydat)</span></code></pre></div>
<pre><code>##                 Var1      Var2     value
## 1  HEEBO-002-CTRL2I1 GSM749899 -1.455124
## 2 HEEBO-002-CTRL2I10 GSM749899  1.044670
## 3 HEEBO-002-CTRL2I11 GSM749899  1.164344
## 4 HEEBO-002-CTRL2I14 GSM749899  1.597227
## 5 HEEBO-002-CTRL2I15 GSM749899 -1.454337
## 6  HEEBO-002-CTRL2I1 GSM749900 -2.624420</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="veri-on-isleme-basamaklari.html#cb203-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mydat,<span class="fu">aes</span>(<span class="at">x =</span> Var1, <span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb203-2"><a href="veri-on-isleme-basamaklari.html#cb203-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape=</span><span class="cn">NA</span>, <span class="at">color =</span> <span class="st">&#39;darkred&#39;</span>) <span class="sc">+</span></span>
<span id="cb203-3"><a href="veri-on-isleme-basamaklari.html#cb203-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">width =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb203-4"><a href="veri-on-isleme-basamaklari.html#cb203-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb203-5"><a href="veri-on-isleme-basamaklari.html#cb203-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&#39;Probeset Expression Value&#39;</span>)</span></code></pre></div>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
</div>
</div>
<div id="probesetid---gen-eslestirmesi" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> ProbesetID - Gen eslestirmesi</h2>
<p>Ayni gen ifade verisi gibi probesetID - gen eslesmesi bilgisinin kayitli oldugu bir tablo daha kaydetmistim. Simdi onu okuyalim:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="veri-on-isleme-basamaklari.html#cb204-1" aria-hidden="true" tabindex="-1"></a>genedata <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&#39;https://github.com/mdonertas/20210322_REgitim/raw/master/data/featuredat.csv&#39;</span>)</span>
<span id="cb204-2"><a href="veri-on-isleme-basamaklari.html#cb204-2" aria-hidden="true" tabindex="-1"></a>genedata[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,]</span></code></pre></div>
<pre><code>##                    X                 ID   OligoID
## 1  HEEBO-002-CTRL2I1  HEEBO-002-CTRL2I1 hCT000577
## 2 HEEBO-002-CTRL2I10 HEEBO-002-CTRL2I10 hCT000586
## 3 HEEBO-002-CTRL2I11 HEEBO-002-CTRL2I11 hCT000587
##                                                                 SEQUENCE
## 1 ACTCTGGATCCTGGGCGACGTCTTCATCGGCCGCTACTACACTGTGTTTGACCGTGACAACAACAGGGTG
## 2 CATCCTCACCGACATCACCAAGGGTGTGCAGTACCTCAACGAGATCAAGGACAGTGTGGTGGCCGGCTTC
## 3 GTCCCTGGAACGCCAGATGCGTGAAATGGAAGAGAACTTTGCCGTTGAAGCTGCTAACTACCAAGACACT
##        GB_ACC Strand Gene_Symbol                                 Gene_Title
## 1 NM_001909.4      +        CTSD                                cathepsin D
## 2 NM_001961.3      +        EEF2 eukaryotic translation elongation factor 2
## 3 NM_003380.3      +         VIM                                   vimentin
##   Entrez_Gene_ID UniGene_Cluster_ID Feb2012_Blast_Cutoffs SPOT_ID
## 1           1509          Hs.654447 100/100_Unique_RefSeq        
## 2           1938          Hs.515070 100/100_Unique_RefSeq        
## 3           7431          Hs.455493 100/100_Unique_RefSeq</code></pre>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="veri-on-isleme-basamaklari.html#cb206-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(genedata)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>Ilk olarak gen bilgisini duzenleyelim. Bunun icin bu data.frame’den iki sutunu kullanacagiz.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="veri-on-isleme-basamaklari.html#cb208-1" aria-hidden="true" tabindex="-1"></a>genedata<span class="sc">$</span>ID[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1] &quot;HEEBO-002-CTRL2I1&quot;  &quot;HEEBO-002-CTRL2I10&quot; &quot;HEEBO-002-CTRL2I11&quot;
##  [4] &quot;HEEBO-002-CTRL2I14&quot; &quot;HEEBO-002-CTRL2I15&quot; &quot;HEEBO-002-CTRL2I16&quot;
##  [7] &quot;HEEBO-002-CTRL2I17&quot; &quot;HEEBO-002-CTRL2I18&quot; &quot;HEEBO-002-CTRL2I19&quot;
## [10] &quot;HEEBO-002-CTRL2I2&quot;</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="veri-on-isleme-basamaklari.html#cb210-1" aria-hidden="true" tabindex="-1"></a>genedata<span class="sc">$</span>Gene_Symbol[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1] &quot;CTSD&quot; &quot;EEF2&quot; &quot;VIM&quot;  &quot;VIM&quot;  &quot;GSN&quot;  &quot;EEF2&quot; &quot;VIM&quot;  &quot;CTSD&quot; &quot;RPN2&quot; &quot;RPN2&quot;</code></pre>
<p>Simdi isimlendirilmis bir vektor olusturacagim ki, belli bir probe IDye karsilik gelen geni bulabileyim. Bunu yapmak icin <code>setNames()</code> fonksiyonunu kullanacagim. Isimler, yani ikinci arguman, probeID olacak, vektorun kendisi ise genler, bu sayede vektoru belli bir probe ID kullanarak subset ettigimde hangi gen oldugunu bulabilirim. Buna gecmeden bir ornek:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="veri-on-isleme-basamaklari.html#cb212-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),<span class="fu">c</span>(<span class="st">&#39;bir&#39;</span>,<span class="st">&#39;iki&#39;</span>,<span class="st">&#39;uc&#39;</span>))</span>
<span id="cb212-2"><a href="veri-on-isleme-basamaklari.html#cb212-2" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## bir iki  uc 
##   1   2   3</code></pre>
<p>ikinci elemani almak icin:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="veri-on-isleme-basamaklari.html#cb214-1" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## iki 
##   2</code></pre>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="veri-on-isleme-basamaklari.html#cb216-1" aria-hidden="true" tabindex="-1"></a>x[<span class="st">&#39;iki&#39;</span>]</span></code></pre></div>
<pre><code>## iki 
##   2</code></pre>
<p>Bunlarin ikisini de kullanabiliyorum. IDleri kullanarak genleri bulmam da ayni sekilde olacak:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="veri-on-isleme-basamaklari.html#cb218-1" aria-hidden="true" tabindex="-1"></a>genemap <span class="ot">=</span> <span class="fu">setNames</span>(genedata<span class="sc">$</span>Gene_Symbol,genedata<span class="sc">$</span>ID)</span>
<span id="cb218-2"><a href="veri-on-isleme-basamaklari.html#cb218-2" aria-hidden="true" tabindex="-1"></a>genemap[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##  HEEBO-002-CTRL2I1 HEEBO-002-CTRL2I10 HEEBO-002-CTRL2I11 HEEBO-002-CTRL2I14 
##             &quot;CTSD&quot;             &quot;EEF2&quot;              &quot;VIM&quot;              &quot;VIM&quot; 
## HEEBO-002-CTRL2I15 
##              &quot;GSN&quot;</code></pre>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="veri-on-isleme-basamaklari.html#cb220-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(genemap)</span></code></pre></div>
<pre><code>##  HEEBO-002-CTRL2I1 HEEBO-002-CTRL2I10 HEEBO-002-CTRL2I11 HEEBO-002-CTRL2I14 
##             &quot;CTSD&quot;             &quot;EEF2&quot;              &quot;VIM&quot;              &quot;VIM&quot; 
## HEEBO-002-CTRL2I15 HEEBO-002-CTRL2I16 
##              &quot;GSN&quot;             &quot;EEF2&quot;</code></pre>
<p>Matrisin satir isimleriyle genemap’i subset ettigimiz zaman, dogru sirayla hangi genlere karsilik geliyorsa bize bu bilgiyi verecek. Simdi once bir yanlis yapma ihtimalimize karsin matrisimizi kopyalayalim:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="veri-on-isleme-basamaklari.html#cb222-1" aria-hidden="true" tabindex="-1"></a>expr_yedek <span class="ot">=</span> expr</span></code></pre></div>
<p>Simdi ilk olarak bir probeset ID birden fazla genle eslesiyor mu buna bakmaliyiz, bunlar veri duplikasyonu yaratacagindan istatistiksel test yapmamizi zorlastirir bunlari veriden cikararak baslayacagiz:</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="veri-on-isleme-basamaklari.html#cb223-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(<span class="fu">names</span>(genemap)))</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Hic tekrar eden bir probesetIDmiz yok - yani bu bu veriseti icin problem degil. Bir de cok fazla sayida probesetIDye map olmus olan genlere bakalim:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="veri-on-isleme-basamaklari.html#cb225-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(genemap),<span class="at">dec=</span>T)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>## genemap
## ##noname##                  LRP1       OCRL       TLN1        TTN      CDH23 
##        903        825         88         62         55         55         41 
##      ANXA7        RB1      DNAH9 
##         40         40         37</code></pre>
<p>Bunlardan <code>'##noname##</code> ve <code>''</code> tabii ki gen ismi degil. Bunlari veriden cikartmak gerekir, ama bunu matrixe isimleri gecirdikten sonra yapacagim. Simdi probeset IDleri gen isimleriyle degistirerek devam edelim:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="veri-on-isleme-basamaklari.html#cb227-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(expr) <span class="ot">=</span> genemap[<span class="fu">rownames</span>(expr)]</span></code></pre></div>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="veri-on-isleme-basamaklari.html#cb228-1" aria-hidden="true" tabindex="-1"></a>expr[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##      GSM749899  GSM749900 GSM749901  GSM749902  GSM749903
## CTSD -1.455124 -2.6244200 -1.904436 -1.5793507 -2.1666262
## EEF2  1.044670  0.4490985  0.619243  0.1930628 -0.4370544
## VIM   1.164344  1.5833201  1.150024  1.5764080  1.3569308
## VIM   1.597227  1.4105770  1.469449  2.6433802  1.7567335
## GSN  -1.454337 -1.9784923 -1.485409 -1.5038039 -1.2828650</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="veri-on-isleme-basamaklari.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(<span class="fu">rownames</span>(expr)), <span class="at">dec =</span> T)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>## 
## ##noname##                  LRP1       OCRL       TLN1        TTN      CDH23 
##        903        825         88         62         55         55         41 
##      ANXA7        RB1      DNAH9 
##         40         40         37</code></pre>
<p>Burada gordugunuz gibi bazi gen isimleri birden fazla kez tekrar ediliyor. Bu mikrodizin dizaynindan kaynakli bir durum, her gen bir ya da daha fazla probeset ile temsil ediliyor. Genelde her gen bu probesetlerin ortalamasi ya da maksimumu alinarak ozetlenir - bu sayede her gen matriste bir defa yer alir. Bunu yapmak icin matrisi gen isimleriyle subset etmeyi ogrenecegiz. Zaten belli bir isimle subset yapmayi biliyoruz, ancak bu sadece tekrarli olmayan durumlarda gecerli. Suna bakalim:</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="veri-on-isleme-basamaklari.html#cb232-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>), <span class="fu">c</span>(<span class="st">&#39;bir&#39;</span>,<span class="st">&#39;iki&#39;</span>,<span class="st">&#39;iki&#39;</span>,<span class="st">&#39;dort&#39;</span>,<span class="st">&#39;bes&#39;</span>))</span>
<span id="cb232-2"><a href="veri-on-isleme-basamaklari.html#cb232-2" aria-hidden="true" tabindex="-1"></a>x[<span class="st">&#39;iki&#39;</span>]</span></code></pre></div>
<pre><code>## iki 
##   2</code></pre>
<p>oysa 3 degerine sahip olan elemanin adi da ‘iki.’ Bu tarz tekrarli durumlarda otomatik olarak ilk eleman verilir. Ikisini birden istiyorsak subset islemini <code>%in%</code> operatoru ile yapmamiz gerekir.</p>
<div id="in-operatoru" class="section level3" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> <code>%in%</code> operatoru</h3>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="veri-on-isleme-basamaklari.html#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;elma&#39;</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;elma&#39;</span>,<span class="st">&#39;armut&#39;</span>)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="veri-on-isleme-basamaklari.html#cb236-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;muz&#39;</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;elma&#39;</span>,<span class="st">&#39;armut&#39;</span>)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="veri-on-isleme-basamaklari.html#cb238-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="st">&#39;elma&#39;</span>, <span class="st">&#39;muz&#39;</span>) <span class="sc">%in%</span> <span class="st">&#39;elma&#39;</span></span></code></pre></div>
<pre><code>## [1]  TRUE FALSE</code></pre>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="veri-on-isleme-basamaklari.html#cb240-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="st">&#39;elma&#39;</span>, <span class="st">&#39;muz&#39;</span>) <span class="sc">%in%</span> <span class="st">&#39;muz&#39;</span></span></code></pre></div>
<pre><code>## [1] FALSE  TRUE</code></pre>
<p>Bilmemiz gereken bir konu da bir vektoru ya da matrisi mantiksal degiskenlerle de subset edebildigimiz:</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="veri-on-isleme-basamaklari.html#cb242-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)[<span class="fu">c</span>(T,T,F,T,F)]</span></code></pre></div>
<pre><code>## [1] 1 2 4</code></pre>
<p>Ilk olarak gen ismi olarak <code>'##noname##</code> ve <code>''</code> gorunen satirlari veriden cikartarak baslamaliyiz:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="veri-on-isleme-basamaklari.html#cb244-1" aria-hidden="true" tabindex="-1"></a>expr <span class="ot">=</span> expr[<span class="sc">!</span><span class="fu">rownames</span>(expr) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;##noname##&#39;</span>,<span class="st">&#39;&#39;</span>),]</span></code></pre></div>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="veri-on-isleme-basamaklari.html#cb245-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">table</span>(<span class="fu">rownames</span>(expr)),<span class="at">dec=</span>T)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>## 
##  LRP1  OCRL  TLN1   TTN CDH23 ANXA7   RB1 DNAH9 WDFY3 SYNE2 
##    88    62    55    55    41    40    40    37    37    36</code></pre>
<p>Simdi tekrar eden genleri ozetlemeye geri donelim.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="veri-on-isleme-basamaklari.html#cb247-1" aria-hidden="true" tabindex="-1"></a>expr[<span class="fu">rownames</span>(expr) <span class="sc">%in%</span> <span class="st">&#39;VIM&#39;</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##     GSM749899 GSM749900 GSM749901 GSM749902 GSM749903
## VIM  1.164344  1.583320  1.150024  1.576408  1.356931
## VIM  1.597227  1.410577  1.469449  2.643380  1.756734
## VIM  2.475041  2.236114  2.179526  2.807048  2.443889
## VIM  2.414010  2.242931  2.379348  1.909755  2.596801
## VIM  2.913906  1.343048  2.536056  2.271887  2.118884
## VIM  1.743049  1.492585  1.621053  1.394594  2.030154
## VIM  1.171174  1.165681  1.099818  2.274270  1.541334
## VIM  1.446696  1.451936  1.782307  2.605349  1.957581
## VIM  1.131674  1.172329  1.053107  1.871871  1.780982</code></pre>
<p>Simdi yeni bir fonksiyon ogrenelim <code>colMeans()</code> bu da adi ustunde sutun ortalamasini aliyor. Yani matrisi tum VIM genine karsilik gelen probesetler icin subset edip, <code>colMeans()</code> dersek tek boyutlu, satirlarin ortalamasina sahip bir vektor verecek:</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="veri-on-isleme-basamaklari.html#cb249-1" aria-hidden="true" tabindex="-1"></a>vimmeans <span class="ot">=</span> <span class="fu">colMeans</span>(expr[<span class="fu">rownames</span>(expr) <span class="sc">%in%</span> <span class="st">&#39;VIM&#39;</span>, ])</span>
<span id="cb249-2"><a href="veri-on-isleme-basamaklari.html#cb249-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vimmeans)</span></code></pre></div>
<pre><code>## GSM749899 GSM749900 GSM749901 GSM749902 GSM749903 GSM749904 
##  1.784125  1.566502  1.696743  2.150507  1.953699  1.409357</code></pre>
<p>Ama bu sadece tek bir gen icin. Oysa biz tek genle ilgilenmiyoruz, butun genler icin bunu yapmak istiyoruz. Eger programlama dillerine asinaysaniz <code>for</code> loop larini duymussunuzdur. Bunlar ayni islemin defalarca ayni ya da farkli inputlar icin tekrarlanmasini saglar. R’da da for loop yazabiliriz bunun icin kullanilacak fonksiyon <code>for</code>. Bizse for yerine R’a ozgu *apply fonksiyonlari olarak gecen fonksiyonlardan biri olan <code>sapply()</code> fonksiyonu ile bunu yapacagiz. Ilk olarak butun gen isimlerini almaliyiz. Bunu sadece <code>rownames()</code> ile alamiyoruz cunku isimler tekrar ediyor. Onun yerine her degerin sadece bir kere tekrar edilmesini <code>unique()</code> fonksiyonu ile saglayacagiz.</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="veri-on-isleme-basamaklari.html#cb251-1" aria-hidden="true" tabindex="-1"></a>genisimleri <span class="ot">=</span> <span class="fu">unique</span>(<span class="fu">rownames</span>(expr))</span>
<span id="cb251-2"><a href="veri-on-isleme-basamaklari.html#cb251-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(expr)</span></code></pre></div>
<pre><code>## [1] 28448</code></pre>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="veri-on-isleme-basamaklari.html#cb253-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(genisimleri)</span></code></pre></div>
<pre><code>## [1] 17160</code></pre>
<p>Sadece 17bin gen var. Yani her gen cok defa tekrar ediliyor olmak zorunda degil. Eger tekrar edilmeyen bir geni subset edersek, ‘sutun ortalamalarini ver’ demek icin kullanacagimiz <code>colMeans</code> fonksiyonu calismaz, cunku bir matris degil bir vektor soz konusu olacak. Bunun icin bir de <code>if</code> fonksiyonunu ogrenmeliyiz. <code>if</code> bir kodu ancak belli kosullar altinda calistiracaktir. Bu sayede eger bir defa geciyorsa sunu yap, birden fazla kez tekrar ediliyorsa sunu yap seklinde bir kod yazmamiz mumkun olacak. If’e cok kisa bir ornek:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="veri-on-isleme-basamaklari.html#cb255-1" aria-hidden="true" tabindex="-1"></a>vektorum <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&#39;elma&#39;</span>,<span class="st">&#39;muz&#39;</span>,<span class="st">&#39;armut&#39;</span>)</span>
<span id="cb255-2"><a href="veri-on-isleme-basamaklari.html#cb255-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="st">&#39;cilek&#39;</span><span class="sc">%in%</span>vektorum){</span>
<span id="cb255-3"><a href="veri-on-isleme-basamaklari.html#cb255-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&#39;cilek var!&#39;</span>)</span>
<span id="cb255-4"><a href="veri-on-isleme-basamaklari.html#cb255-4" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> <span class="cf">if</span>(<span class="st">&#39;elma&#39;</span> <span class="sc">%in%</span> vektorum){</span>
<span id="cb255-5"><a href="veri-on-isleme-basamaklari.html#cb255-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&#39;elma var!&#39;</span>)</span>
<span id="cb255-6"><a href="veri-on-isleme-basamaklari.html#cb255-6" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span>{</span>
<span id="cb255-7"><a href="veri-on-isleme-basamaklari.html#cb255-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&#39;ne cilek ne elma var :(&#39;</span>)</span>
<span id="cb255-8"><a href="veri-on-isleme-basamaklari.html#cb255-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;elma var!&quot;</code></pre>
<p>daha iyi anlayabilmemiz icin bir ornek daha:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="veri-on-isleme-basamaklari.html#cb257-1" aria-hidden="true" tabindex="-1"></a>vektorum <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&#39;elma&#39;</span>,<span class="st">&#39;muz&#39;</span>,<span class="st">&#39;armut&#39;</span>)</span>
<span id="cb257-2"><a href="veri-on-isleme-basamaklari.html#cb257-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="st">&#39;muz&#39;</span><span class="sc">%in%</span>vektorum){</span>
<span id="cb257-3"><a href="veri-on-isleme-basamaklari.html#cb257-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&#39;muz var!&#39;</span>)</span>
<span id="cb257-4"><a href="veri-on-isleme-basamaklari.html#cb257-4" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> <span class="cf">if</span>(<span class="st">&#39;elma&#39;</span> <span class="sc">%in%</span> vektorum){</span>
<span id="cb257-5"><a href="veri-on-isleme-basamaklari.html#cb257-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&#39;elma var!&#39;</span>)</span>
<span id="cb257-6"><a href="veri-on-isleme-basamaklari.html#cb257-6" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span>{</span>
<span id="cb257-7"><a href="veri-on-isleme-basamaklari.html#cb257-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&#39;ne cilek ne elma var :(&#39;</span>)</span>
<span id="cb257-8"><a href="veri-on-isleme-basamaklari.html#cb257-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;muz var!&quot;</code></pre>
<p>hem elma hem muz olmasina ragmen sadece birinci komut calisti. Bunun sebebi <code>else</code> komutu ancak ilk kodumuz yanlissa calisacak olmasi.</p>
<p>Simdi de cok kisa <code>sapply()</code> nasil calisiyor buna bakalim:</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="veri-on-isleme-basamaklari.html#cb259-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>),<span class="cf">function</span>(i){</span>
<span id="cb259-2"><a href="veri-on-isleme-basamaklari.html#cb259-2" aria-hidden="true" tabindex="-1"></a>  i <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb259-3"><a href="veri-on-isleme-basamaklari.html#cb259-3" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div>
<pre><code>##  [1]  2  4  6  8 10 12 14 16 18 20</code></pre>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="veri-on-isleme-basamaklari.html#cb261-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>),<span class="cf">function</span>(i){</span>
<span id="cb261-2"><a href="veri-on-isleme-basamaklari.html#cb261-2" aria-hidden="true" tabindex="-1"></a>  i <span class="sc">*</span> (i<span class="dv">-1</span>)</span>
<span id="cb261-3"><a href="veri-on-isleme-basamaklari.html#cb261-3" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div>
<pre><code>##  [1]  0  2  6 12 20 30 42 56 72 90</code></pre>
<p>Simdi biraz ileri duzey gibi gorunmesi muhtemel bir kod yazacagiz ama basamak basamak inceleyince anlasilmasi kolay olacaktir:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="veri-on-isleme-basamaklari.html#cb263-1" aria-hidden="true" tabindex="-1"></a>genexpr <span class="ot">=</span> <span class="fu">sapply</span>(genisimleri, <span class="cf">function</span>(gen) {</span>
<span id="cb263-2"><a href="veri-on-isleme-basamaklari.html#cb263-2" aria-hidden="true" tabindex="-1"></a>  i <span class="ot">=</span> <span class="fu">rownames</span>(expr)<span class="sc">%in%</span>gen</span>
<span id="cb263-3"><a href="veri-on-isleme-basamaklari.html#cb263-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="fu">sum</span>(i)<span class="sc">&gt;</span><span class="dv">1</span>){</span>
<span id="cb263-4"><a href="veri-on-isleme-basamaklari.html#cb263-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">colMeans</span>(expr[i,])</span>
<span id="cb263-5"><a href="veri-on-isleme-basamaklari.html#cb263-5" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span>(<span class="fu">sum</span>(i)<span class="sc">==</span><span class="dv">1</span>){</span>
<span id="cb263-6"><a href="veri-on-isleme-basamaklari.html#cb263-6" aria-hidden="true" tabindex="-1"></a>    expr[i,]</span>
<span id="cb263-7"><a href="veri-on-isleme-basamaklari.html#cb263-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb263-8"><a href="veri-on-isleme-basamaklari.html#cb263-8" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="veri-on-isleme-basamaklari.html#cb264-1" aria-hidden="true" tabindex="-1"></a>genexpr[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##                 CTSD      EEF2      VIM        GSN     RPN2
## GSM749899 -0.8124619 1.5620237 1.784125 -0.6578933 1.658038
## GSM749900 -1.3310489 1.4339156 1.566502 -1.1007844 1.528385
## GSM749901 -1.2447029 0.9832866 1.696743 -1.0306526 1.286318
## GSM749902 -1.2017866 0.7393814 2.150507 -0.8413292 1.153392
## GSM749903 -1.1041998 0.2957918 1.953699 -0.7242716 0.789019</code></pre>
<p>satir-sutun yer degistirmis durumda. bunu yine transpoze ederek duzeltebiliriz:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="veri-on-isleme-basamaklari.html#cb266-1" aria-hidden="true" tabindex="-1"></a>genexpr <span class="ot">=</span> <span class="fu">t</span>(genexpr)</span></code></pre></div>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="veri-on-isleme-basamaklari.html#cb267-1" aria-hidden="true" tabindex="-1"></a>genexpr[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##       GSM749899 GSM749900  GSM749901  GSM749902  GSM749903
## CTSD -0.8124619 -1.331049 -1.2447029 -1.2017866 -1.1041998
## EEF2  1.5620237  1.433916  0.9832866  0.7393814  0.2957918
## VIM   1.7841245  1.566502  1.6967431  2.1505070  1.9536987
## GSN  -0.6578933 -1.100784 -1.0306526 -0.8413292 -0.7242716
## RPN2  1.6580375  1.528385  1.2863177  1.1533917  0.7890190</code></pre>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="veri-on-isleme-basamaklari.html#cb269-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(genexpr)</span></code></pre></div>
<pre><code>## [1] 17160   269</code></pre>
<p>Artik her gen icin bir satirimiz var!</p>
</div>
</div>
<div id="quantile-normalization" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Quantile Normalization</h2>
<p>Son olarak bu gen ifade matrixinde bir normalizasyon metodu uygulayalim. Burada amacimiz farkli ornekler arasindaki olasi teknik varyasyonu ortadan kaldirmak. Uygulayacagimiz normalizasyonun adi ‘quantile normalization’ - bunun sonunda tum orneklerin dagilimlari ayni olacak - genler farkli degerler alacak ama genlerin dagilimi ayni olacak. Normalizasyon oncesi ilk bir kac bireyin dagilimina bakalim.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="veri-on-isleme-basamaklari.html#cb271-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(genexpr[,<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>])</span></code></pre></div>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-92-1.png" width="672" />
Gordugunuz gibi ortalamalari hemen hemen ayni olsa da (bunun sebebi verinin zaten baska bir yontemle kismen normalize edilmis olmasi), Dagilimlar farkli.</p>
<p>Normalizasyon icin Rda olmayan bir fonksiyon kullanacagiz, bunun icin de <code>preprocessCore</code> paketini yuklememiz gerekiyor:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="veri-on-isleme-basamaklari.html#cb272-1" aria-hidden="true" tabindex="-1"></a>BiocManager<span class="sc">::</span><span class="fu">install</span>(<span class="st">&quot;preprocessCore&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="veri-on-isleme-basamaklari.html#cb273-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(preprocessCore)</span></code></pre></div>
<p>Fonksiyonumuzun adi <code>normalize.quantiles()</code></p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="veri-on-isleme-basamaklari.html#cb274-1" aria-hidden="true" tabindex="-1"></a>genexpr_qn <span class="ot">=</span> <span class="fu">normalize.quantiles</span>(genexpr)</span>
<span id="cb274-2"><a href="veri-on-isleme-basamaklari.html#cb274-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(genexpr_qn)</span></code></pre></div>
<pre><code>## [1] 17160   269</code></pre>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="veri-on-isleme-basamaklari.html#cb276-1" aria-hidden="true" tabindex="-1"></a>genexpr_qn[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##            [,1]       [,2]       [,3]       [,4]       [,5]
## [1,] -0.4993920 -0.6776740 -0.7796459 -0.8040486 -0.8587960
## [2,]  1.0141904  0.8355595  0.6704056  0.5563232  0.2924776
## [3,]  1.1413791  0.9140343  1.1026208  1.4685350  1.5103426
## [4,] -0.4112961 -0.5602207 -0.6620208 -0.5704519 -0.6015157
## [5,]  1.0659865  0.8908564  0.8555507  0.8361596  0.6749602</code></pre>
<p>Gordugunuz gibi bu fonksiyon ne yazik ki satir sutun isimlerimizi sildi. Ama bunlarin ilk matrisimizle ayni oldugunu biliyoruz cunku bir subset islemi yapmadik. Eski satir-sutun isimlerimizi yeni matrisimize aktaralim:</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="veri-on-isleme-basamaklari.html#cb278-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dimnames</span>(genexpr_qn) <span class="ot">=</span> <span class="fu">dimnames</span>(genexpr)</span>
<span id="cb278-2"><a href="veri-on-isleme-basamaklari.html#cb278-2" aria-hidden="true" tabindex="-1"></a>genexpr_qn[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##       GSM749899  GSM749900  GSM749901  GSM749902  GSM749903
## CTSD -0.4993920 -0.6776740 -0.7796459 -0.8040486 -0.8587960
## EEF2  1.0141904  0.8355595  0.6704056  0.5563232  0.2924776
## VIM   1.1413791  0.9140343  1.1026208  1.4685350  1.5103426
## GSN  -0.4112961 -0.5602207 -0.6620208 -0.5704519 -0.6015157
## RPN2  1.0659865  0.8908564  0.8555507  0.8361596  0.6749602</code></pre>
<p>Tekrar dagilimlara bakacak olursak:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="veri-on-isleme-basamaklari.html#cb280-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(genexpr_qn[,<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>])</span></code></pre></div>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
<p>Gordugunuz gibi dagilimlar birebir esit oldu. Bundan sonraki asamalarda bu veriyi kullanacagiz.</p>
</div>
<div id="ornek-bilgisini-duzenleme" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Ornek bilgisini duzenleme</h2>
<p>Son olarak, bir de orneklerle ilgili bilgilerin yer aldigi (yas, biyolojik cinsiyet) bir tablomuz var. Ama bu verinin de duzenlenmesi gerekiyor.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="veri-on-isleme-basamaklari.html#cb281-1" aria-hidden="true" tabindex="-1"></a>metadata <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&#39;https://github.com/mdonertas/20210322_REgitim/raw/master/data/metadata.csv&#39;</span>)</span>
<span id="cb281-2"><a href="veri-on-isleme-basamaklari.html#cb281-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(metadata)</span></code></pre></div>
<pre><code>##           X    title geo_accession characteristics_ch1 characteristics_ch1.1
## 1 GSM749899 HB_18_34     GSM749899     array batch: 10     age: -0.498630137
## 2 GSM749900 HB_22_35     GSM749900     array batch: 18     age: -0.498630137
## 3 GSM749901 HB_16_29     GSM749901      array batch: 1     age: -0.498630137
## 4 GSM749902 HB_17_91     GSM749902      array batch: 8     age: -0.498630137
## 5 GSM749903 HB_18_16     GSM749903      array batch: 9     age: -0.479452055
## 6 GSM749904 HB_16_62     GSM749904      array batch: 3     age: -0.479452055
##   characteristics_ch1.2 characteristics_ch1.3        characteristics_ch1.4
## 1                Sex: F              race: AA postmortem interval (pmi): 3
## 2                Sex: F              race: AA postmortem interval (pmi): 1
## 3                Sex: M              race: AA postmortem interval (pmi): 1
## 4                Sex: M              race: AA postmortem interval (pmi): 4
## 5                Sex: M              race: AA postmortem interval (pmi): 2
## 6                Sex: M              race: AA postmortem interval (pmi): 4
##   characteristics_ch1.5           characteristics_ch1.6   characteristics_ch1.7
## 1              ph: NULL rna integrity number (rin): 9.7      smoke at death: No
## 2              ph: 6.21 rna integrity number (rin): 9.8      smoke at death: No
## 3              ph: NULL rna integrity number (rin): 9.6      smoke at death: No
## 4              ph: NULL rna integrity number (rin): 9.8      smoke at death: No
## 5              ph: NULL   rna integrity number (rin): 9 smoke at death: Unknown
## 6              ph: NULL rna integrity number (rin): 9.8      smoke at death: No</code></pre>
<p>Bu veriyi kullanarak, ayni probeset-gen eslestirmesi icin yaptigimiz gibi yas ve biyolojik cinsiyet icin birey bilgisi vektoru olusturalim:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="veri-on-isleme-basamaklari.html#cb283-1" aria-hidden="true" tabindex="-1"></a>yas <span class="ot">=</span> <span class="fu">setNames</span>(metadata<span class="sc">$</span>characteristics_ch1<span class="fl">.1</span>, metadata<span class="sc">$</span>geo_accession)</span>
<span id="cb283-2"><a href="veri-on-isleme-basamaklari.html#cb283-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(yas)</span></code></pre></div>
<pre><code>##           GSM749899           GSM749900           GSM749901           GSM749902 
## &quot;age: -0.498630137&quot; &quot;age: -0.498630137&quot; &quot;age: -0.498630137&quot; &quot;age: -0.498630137&quot; 
##           GSM749903           GSM749904 
## &quot;age: -0.479452055&quot; &quot;age: -0.479452055&quot;</code></pre>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="veri-on-isleme-basamaklari.html#cb285-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(yas)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="veri-on-isleme-basamaklari.html#cb287-1" aria-hidden="true" tabindex="-1"></a>cinsiyet <span class="ot">=</span> <span class="fu">setNames</span>(metadata<span class="sc">$</span>characteristics_ch1<span class="fl">.2</span>, metadata<span class="sc">$</span>geo_accession)</span>
<span id="cb287-2"><a href="veri-on-isleme-basamaklari.html#cb287-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cinsiyet)</span></code></pre></div>
<pre><code>## GSM749899 GSM749900 GSM749901 GSM749902 GSM749903 GSM749904 
##  &quot;Sex: F&quot;  &quot;Sex: F&quot;  &quot;Sex: M&quot;  &quot;Sex: M&quot;  &quot;Sex: M&quot;  &quot;Sex: M&quot;</code></pre>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="veri-on-isleme-basamaklari.html#cb289-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(cinsiyet)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Bu veriler gordugunuz gibi karakter verileri ve formatlari pek iyi degil. Ornegin bu yas verisiyle yapabileceklerimiz sinirli cunku numerik degil. Ilk olarak basta yazan ‘age:’ kismindan kurtulmamiz lazim ki bu yas verisini kullanabilelim. Ayni sekilde biyolojik cinsiyeti de ‘F’ veya ‘M’ haline, hatta daha iyisi ‘kadin’ ve ‘erkek’ haline getirelim.</p>
<div id="yas-verisinin-duzenlenmesi" class="section level3" number="5.5.1">
<h3><span class="header-section-number">5.5.1</span> Yas verisinin duzenlenmesi</h3>
<p>Basta yazan ‘age:’ yazisinin ortadan kaldirilmasi icin bir kac secenek var. Bunlardan en basiti <code>gsub</code> fonksiyonu. Bu fonksiyon, bir karakter vektorunde belli karakterlerin degistirilmesini saglar:</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="veri-on-isleme-basamaklari.html#cb291-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gsub</span>(<span class="st">&#39;range&#39;</span>,<span class="st">&#39;&#39;</span>,<span class="st">&#39;Bioinforange&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Bioinfo&quot;</code></pre>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="veri-on-isleme-basamaklari.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gsub</span>(<span class="st">&#39;range&#39;</span>,<span class="st">&#39;conference&#39;</span>,<span class="st">&#39;Bioinforange&#39;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Bioinfoconference&quot;</code></pre>
<p>Bu sekilde ‘age:’ yazisini silebiliriz:</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="veri-on-isleme-basamaklari.html#cb295-1" aria-hidden="true" tabindex="-1"></a>yas <span class="ot">=</span> <span class="fu">gsub</span>(<span class="st">&#39;age: &#39;</span>,<span class="st">&#39;&#39;</span>,yas)</span>
<span id="cb295-2"><a href="veri-on-isleme-basamaklari.html#cb295-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(yas)</span></code></pre></div>
<pre><code>##      GSM749899      GSM749900      GSM749901      GSM749902      GSM749903 
## &quot;-0.498630137&quot; &quot;-0.498630137&quot; &quot;-0.498630137&quot; &quot;-0.498630137&quot; &quot;-0.479452055&quot; 
##      GSM749904 
## &quot;-0.479452055&quot;</code></pre>
<p>Ancak gordugunuz gibi, veri hala karakter. Bunu numerik yapmak icin <code>as.numeric()</code> kullaniriz:</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="veri-on-isleme-basamaklari.html#cb297-1" aria-hidden="true" tabindex="-1"></a>yas <span class="ot">=</span> <span class="fu">setNames</span>(<span class="fu">as.numeric</span>(yas),<span class="fu">names</span>(yas))</span></code></pre></div>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="veri-on-isleme-basamaklari.html#cb298-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(yas)</span></code></pre></div>
<p><img src="20210322_REgitim_files/figure-html/unnamed-chunk-103-1.png" width="672" /></p>
<p>Daha net bir sekilde verinin ozetini gormek istersek <code>summary()</code> fonksiyonunu kullanabiliriz:</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="veri-on-isleme-basamaklari.html#cb299-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(yas)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -0.4986  5.3452 24.2658 27.7920 46.9671 78.2274</code></pre>
<p>Dogum oncesi zamandan 78 yasina kadar bireyler var ve ortalamamiz 27.7.</p>
</div>
<div id="biyolojik-cinsiyet-verisinin-duzenlenmesi" class="section level3" number="5.5.2">
<h3><span class="header-section-number">5.5.2</span> Biyolojik cinsiyet verisinin duzenlenmesi</h3>
<p>Bu sefer sadece 2 biyolojik cinsiyet mumkun oldugundan daha farkli bir yol izleyebiliriz. Ama oncelikle, sadece iki secenek oldugundan emin olalim.</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="veri-on-isleme-basamaklari.html#cb301-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(cinsiyet)</span></code></pre></div>
<pre><code>## [1] &quot;Sex: F&quot; &quot;Sex: M&quot; &quot;Sex: 5&quot;</code></pre>
<p>Bir de ‘5’ var, bu muhtemelen veri girisinde bir hata demek ama bu bireyi en azindan cinsiyet icin inceleyemeyecegimiz anlamina geliyor. Ilk olarak bu veriye sahip olan bireyi hem bu veriden hem expression verisinden hem de yas verisinden cikaralim.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="veri-on-isleme-basamaklari.html#cb303-1" aria-hidden="true" tabindex="-1"></a>cikart <span class="ot">=</span> <span class="fu">names</span>(cinsiyet[(cinsiyet <span class="sc">%in%</span> <span class="st">&#39;Sex: 5&#39;</span>)])</span>
<span id="cb303-2"><a href="veri-on-isleme-basamaklari.html#cb303-2" aria-hidden="true" tabindex="-1"></a>cinsiyet <span class="ot">=</span> cinsiyet[<span class="sc">!</span><span class="fu">names</span>(cinsiyet) <span class="sc">%in%</span> cikart]</span>
<span id="cb303-3"><a href="veri-on-isleme-basamaklari.html#cb303-3" aria-hidden="true" tabindex="-1"></a>yas <span class="ot">=</span> yas[<span class="sc">!</span><span class="fu">names</span>(yas) <span class="sc">%in%</span> cikart]</span>
<span id="cb303-4"><a href="veri-on-isleme-basamaklari.html#cb303-4" aria-hidden="true" tabindex="-1"></a>genexpr_qn <span class="ot">=</span> genexpr_qn[,<span class="sc">!</span><span class="fu">colnames</span>(genexpr_qn) <span class="sc">%in%</span> cikart]</span></code></pre></div>
<p>Ayni probeset-gen eslesmesi yapmak icin kullandigimiz gibi bir vektor olusturalim:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="veri-on-isleme-basamaklari.html#cb304-1" aria-hidden="true" tabindex="-1"></a>cinsiyetMap <span class="ot">=</span> <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">&#39;Kadin&#39;</span>,<span class="st">&#39;Erkek&#39;</span>),<span class="fu">c</span>(<span class="st">&#39;Sex: F&#39;</span>,<span class="st">&#39;Sex: M&#39;</span>))</span>
<span id="cb304-2"><a href="veri-on-isleme-basamaklari.html#cb304-2" aria-hidden="true" tabindex="-1"></a>cinsiyet <span class="ot">=</span> <span class="fu">setNames</span>(cinsiyetMap[cinsiyet],<span class="fu">names</span>(cinsiyet))</span>
<span id="cb304-3"><a href="veri-on-isleme-basamaklari.html#cb304-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cinsiyet)</span></code></pre></div>
<pre><code>## GSM749899 GSM749900 GSM749901 GSM749902 GSM749903 GSM749904 
##   &quot;Kadin&quot;   &quot;Kadin&quot;   &quot;Erkek&quot;   &quot;Erkek&quot;   &quot;Erkek&quot;   &quot;Erkek&quot;</code></pre>
<p>Kac kadin kac erkek bireyin olduguna bakmak icin <code>table()</code> fonksiyonunu kullanabiliriz:</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="veri-on-isleme-basamaklari.html#cb306-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(cinsiyet)</span></code></pre></div>
<pre><code>## cinsiyet
## Erkek Kadin 
##   177    91</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="insan-prefrontal-korteksinde-gen-ifadesinin-zamansal-dinamikleri.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="temel-bilesenler-analizi.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["20210322_REgitim.pdf", "20210322_REgitim.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
